config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "dashboard", to: 'pages#dashboard'
  resources :beasts do
    resources :rentals
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :beasts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/availability.rb
class Availability < ApplicationRecord
  belongs_to :beast
  validates :start_date, :end_date, presence: true
  include PgSearch::Model
  pg_search_scope :global_search,
    against: [ :start_date, :end_date ],
    associated_against: {
      beast: [ :name, :species, :gender, :bio ]
    },
    using: {
      tsearch: { prefix: true }
    }
end

app/models/beast.rb
class Beast < ApplicationRecord
  belongs_to :user
  has_many :rentals, dependent: :destroy
  has_many :availabilities, dependent: :destroy
  has_many_attached :photos
  validates :species, inclusion: { in: %w(Quadruped Fish Bird Mollusc Insect Monkey) }
  validates :date_of_birth, :gender, :name, :photos, presence: true
  include PgSearch::Model
  pg_search_scope :global_search,
    against: [ :name, :species, :gender, :bio ],
    associated_against: {
      user: [ :first_name, :last_name, :address, :bio ]
    },
    using: {
      tsearch: { prefix: true }
    }
end

app/models/rental.rb
class Rental < ApplicationRecord
  STATUS = %w(Confirmed Pending Canceled Refused Done)
  belongs_to :user
  belongs_to :beast
  validates :start_date, :end_date, presence: true
  # validates :status, inclusion: { in: STATUS }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :rental
  validates :content, :rating, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :beasts, dependent: :destroy
  has_many :rentals
  has_one_attached :photo
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :address, :bio, :photo])
    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :address, :bio, :photo])
  end
end

app/controllers/beasts_controller.rb
class BeastsController < ApplicationController
  before_action :set_beast, only: [ :show, :destroy, :edit, :update ]
  before_action :set_user

  def new
    @beast = Beast.new
  end

  def create
    @beast = Beast.new(beast_params)
    @beast.user_id = @user.id
    if @beast.save!
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def index
    @beasts = Beast.all
    if params[:query].present?
      @beasts = Beast.global_search(params[:query])
    else
      @beasts = Beast.all
    end
    @markers = @beasts.map do |beast|
      {
        lat: beast.user.latitude,
        lng: beast.user.longitude,
        info_window: render_to_string(partial: "info_window", locals: { beast: beast }),
        image_url: helpers.asset_url("https://res.cloudinary.com/dngfqo2nf/image/upload/v1645651388/IconesWeb/icone-map-vert_hrn1un.png")
      }
    end
  end

  def show
    @rental = Rental.new
  end

  def edit
  end

  def update
    @beast.update(beast_params)
    redirect_to beast_path(@beast)
  end

  def destroy
    @beast.destroy
    redirect_to root_path
  end

  private

  def beast_params
    params.require(:beast).permit(:name, :gender, :date_of_birth, :species, :bio, photos: [])
  end

  def set_beast
    @beast = Beast.find(params[:id])
  end

  def set_user
    @user = current_user
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @user = current_user
    @beasts = Beast.all
    @selection = @beasts.sample(5)
  end

  def dashboard
    @user = current_user
    @rentals = @user.rentals
  end

end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :set_rental, only: :show
  before_action :set_user

  def index
    @rentals = Rental.where(user_id: current_user.id)
    @user = current_user
  end

  def show
    @user = current_user
  end

  def new
  end

  def create
    @beast = Beast.find(params[:beast_id])
    @rental = Rental.new(rental_params)
    @rental.beast = @beast
    @rental.user = @user
    if @rental.save
      redirect_to dashboard_path
    else
      render 'beasts/show'
    end
  end

  private

  def set_rental
    @rental = Rental.find(params[:id])
  end

  def set_user
    @user = current_user
  end

  def rental_params
    params.require(:rental).permit(:start_date, :end_date)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
    @review = Review.find(params[:review_id])
  end

  def create
    @review = Review.new(review_params)
    @review = Review.find(params[:review_id])
    @review.review = @review
    if @review.save
      redirect_to review_path(params[:review_id])
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/beasts/_beast_form.html.erb
       <!-- Modal -->
      <div class="modal fade" id="modalNewBeast" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Add a beast ...</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <%= simple_form_for(Beast.new) do |f| %>
                <%= f.input :name %>
                <%= f.input :gender, collection: %w(male female) %>
                <%= f.input :species, collection: %w(Quadruped Fish Bird Mollusc Insect Monkey) %>
                <%= f.input :bio %>
                <%= f.input :date_of_birth, html5: true %>
                <%= f.input :photos, as: :file, input_html: { multiple: true} %>
            </div>
            <div class="modal-footer">
                <%= f.submit %>
              <% end %>
            </div>
          </div>
        </div>
      </div>

app/views/beasts/_info_window.html.erb
<% beast.user.beasts.each do |bea| %>
  <h2>
  <%= bea.name %>
  </h2>
<% end %>
<p><%= beast.user.address %></p>

app/views/beasts/_modal_beast_form.erb
<div class="modal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Add a beast to your profile :</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= simple_form_for(beast) do |f| %>
          <%= f.input :name %>
          <%= f.input :gender, collection: %w(male female) %>
          <%= f.input :species, collection: %w(Quadruped Fish Bird Mollusc Insect Monkey) %>
          <%= f.input :bio %>
          <%= f.input :date_of_birth, html5: true %>
          <%= f.input :photos, as: :file, input_html: { multiple: true} %>
          <%= f.submit %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save your beast</button>
      </div>
    </div>
  </div>
</div>

app/views/beasts/edit.html.erb
<h1>Edit your beast</h1>
<%= render "beast_form", beast: @beast %>

app/views/beasts/index.html.erb
<%= render "shared/navbar" %>

<div class="site-content">
  <div class="beasts-list ps-5 pe-5 col-7">

    <h3 class="index-title">Ranking by relevance</h3>

      <% if @beasts %>
      <% @beasts.each do |beast| %>

        <%= link_to beast_path(beast) do %>
          <div class="beast-card card my-4 d-flex flex-row">
            <%= cl_image_tag beast.photos.first.key, class: "img-placeholder", style: "background-image", crop: :fill %>
            <div class="card-infos ms-4 d-flex justify-content-between flex-column">
              <div class="top-card">
                <h6>Species: <%= beast.species %> - Owner: <%= beast.user.first_name.capitalize %></h6>
                <h3><%= beast.name.capitalize %></h3>
              </div>

              <div class="middle-card">
                <p>Date of birth: <%=beast.date_of_birth %></p>
                <p>Paris, France</p>
                <p>Bio: "<%= beast.bio %>"</p>
              </div>

              <div class="reviews d-flex align-items-center">
                <i class="fa-solid fa-star"></i>
                <p class="review mx-2 py-2 my-0">
                  <span class="note"><%= (rand(3.3..5)).round(2) %></span> • (<%= rand(4..50) %> reviews)
                </p>
              </div>

            </div>
          </div>
          <hr>
        <% end %>

      <%end %>
      <% else %>
        <div class="top-card">
          <h3>Well, there's no one here, sorry...</h3>
        </div>
      <% end %>

  </div>

<div
  class="map col-5 ms-5"
  data-controller="mapbox"
  data-mapbox-markers-value="<%= @markers.to_json %>"
  data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
</div>

app/views/beasts/new.html.erb
<h1>Create a beast</h1>
<%= render "beast_form", beast: @beast %>

app/views/beasts/show.html.erb
<%= render "shared/navbar" %>

<div class="container mt-3 pt-3">
  <div class="header-show">

    <h6 class="return-section my-2 py-2">
      <i class="fa-solid fa-arrow-left-long"></i>
      <a class="link-return mx-2" href="/beasts">Go back to index</a>
    </h6>

    <h3>Look how cute is <%= @beast.name %>! Want to pet it?</h3>

    <div class="reviews d-flex mb-5 align-items-center">
      <i class="fa-solid fa-star"></i>
      <p class="review mx-2 py-2 my-0">
        <span class="note"><%= (rand(3.3..5)).round(2) %></span> • (<%= rand(4..50) %> reviews)
        <span id="location">Location: Paris, France</span>
      </p>
    </div>
  </div>

  <div class="show-content d-flex">

    <div class="col-7 me-4">
      <% @beast.photos.each do |photo| %>
        <%= cl_image_tag photo.key, crop: :fill, class: "image-show" %>
      <% end %>
    </div>

    <div class="calendar-card col-5">
      <h4 class="my-3">Add dates to book</h4>
      <%= simple_form_for [@beast, @rental] do |f| %>
        <div class="d-flex justify-content-between">
          <div class="border rounded p-2 me-1 col-6">
            <%= f.input :start_date, label: "Start date", placeholder: 'When?', html5: true%>
          </div>
          <div class="border rounded p-2 col-6">
            <%= f.input :end_date, html5: true %>
          </div>
        </div>
        <%= f.button :submit, label: "End date", class: "btn-submit-green"%>
      <% end %>
    </div>
  </div>

  <div class="owner-section my-5 col-6 py-4">
    <div class="top-section d-flex align-items-center">

        <%# ici  %>


      <% if @beast.user.photo.key.nil? %>
      <%= image_tag "https://res.cloudinary.com/dngfqo2nf/image/upload/w_1000,ar_1:1,c_fill,g_auto,e_art:hokusai/v1645787355/production/2u56hzrwakl8ztsse6yxrvyevzxk.jpg", :gravity=>"face", :height=>40, :radius=>30, :width=>40, :crop=>"fill", class: "avatar-large me-2" %>

      <% else %>
      <%= cl_image_tag @beast.user.photo.key, :gravity=>"face", :height=>40, :radius=>30, :width=>40, :crop=>"fill", class: "avatar-large me-2" %>


      <% end %>

      <div class="text-wrapper">
        <h4 class="my-1">Owner: <%= @beast.user.first_name %> <%= @beast.user.last_name %></h4>
        <p class="my-1">Hello, I am the proud owner of <%= @beast.name %></p>
      </div>
    </div>
    <hr class="mb-4">
    <p class="description-owner"><%= @beast.user.bio %></p>
  </div>
  <br>
</div>


<footer class="footer mt-5 w-100">
  <div class="top">
    <p>Ready for an unforgettable experience?</p>
    <h2>Sign up now!</h2>
    <a href="#" class="btn btn-default my-4">Get me in!</a>
  </div>
  <p>Copyright © 2022. airbnbeast. All rights reserved.</p>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Airbnbeast</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <script defer src="https://kit.fontawesome.com/c2b6fbe930.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
    <%= render "beasts/beast_form" %>

  </body>
</html>

app/views/pages/_dropdown_user.html.erb
<% if user_signed_in? %>
  <div class="dropdown">
    <button class="btn btn-dropdown " type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
      <span><%= user.first_name %></span> <span class="me-2"><%= user.last_name %></span>

        <% if user.photo.key.nil? %>
          <%= image_tag "https://res.cloudinary.com/dngfqo2nf/image/upload/w_1000,ar_1:1,c_fill,g_auto,e_art:hokusai/v1645787355/production/2u56hzrwakl8ztsse6yxrvyevzxk.jpg", :gravity=>"face", :height=>40, :radius=>30, :width=>40, :crop=>"fill", class: "avatar" %>

        <% else %>

          <%= cl_image_tag user.photo.key, :gravity=>"face", :height=>40, :radius=>30, :width=>40, :crop=>"fill", class: "avatar" %>

        <% end %>
    </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
        <%= link_to "my dashboard", dashboard_path, class:"dropdown-item" %>
        <%= link_to "my profile", edit_user_registration_path, class:"dropdown-item" %>
      <button type="button" class="dropdown-item" data-bs-toggle="modal" data-bs-target="#modalNewBeast">
        add new beast
      </button>
        <%= link_to "log out", destroy_user_session_path, method: :delete, class:"dropdown-item" %>
    </ul>
  </div>

<% else %>
  <%= link_to "log in", new_user_session_path, class:"no-avatar" %>
<% end %>

app/views/pages/dashboard.html.erb
<!--Compte le nombre de in progress -->
<% icours = 0 %>
<% @rentals.each do |rental| %>
<% if ((Date.parse(rental.start_date.to_s).to_time.to_i - Time.now.to_i) < 0) &&
       ((Date.parse(rental.end_date.to_s).to_time.to_i - Time.now.to_i) > 0)  %>
<% icours += 1 %>
<% end %>
<% end %>

<!--Compte le nombre de My reservations -->
<% ireservations = 0 %>
<% @rentals.each do |rental| %>
<% if (Date.parse(rental.start_date.to_s).to_time.to_i - Time.now.to_i) > 0 %>
<% ireservations += 1 %>
<% end %>
<% end %>

<!--Compte le nombre de My past reservations -->
<% ipastreservations = 0 %>
<% @rentals.each do |rental| %>
<% if (Date.parse(rental.start_date.to_s).to_time.to_i - Time.now.to_i) < 0 %>
<% ipastreservations += 1 %>
<% end %>
<% end %>

<%= render "shared/navbar" %>

<section class="header-wrapper jumbotron text-center py-3 mt-4">
  <div class="container">
    <h1 class="jumbotron-heading mt-4">My Dashboard</h1>
    <p class="lead text-muted mb-4">Find all the information concerning your reservations below.</p>
    <p>



      <%# <a href="/beasts/new" class="btn btn-primary my-2">Add a beast to rent</a> %>
      <button type="button" class="btn btn-primary my-2 btn-greeen" data-bs-toggle="modal" data-bs-target="#modalNewBeast">
        add new beast to rent
      </button>




      <a href="/" class="btn btn-secondary my-2">Go back to airbnbeast</a>
    </p>
  </div>
</section>

<hr class="col-6 offset-3 mb-5">

<div class="container w-100 my-5 py-4">
  <div class="cards-wrapper d-flex justify-content-around">

    <div class="card-box p-5 col-5">
      <div class="d-flex justify-content-between align-items-center border-bottom pb-2">
        <h2>Your beasts</h2>
        <%= link_to new_beast_path do %>
        <i class="fa-solid fa-plus"></i>
        <% end %>
      </div>
      <p class="pt-2">You have <strong><%= @user.beasts.length %></strong> beasts in your dashboard</p>
      <div class="d-flex flex-column scrollable-card">
        <% @user.beasts.each do |beast| %>
          <%= link_to beast_path(beast) do %>
            <div class="card-product">
              <%= cl_image_tag beast.photos.first.key %>
              <div class="card-product-infos d-flex">
                <h2><%= beast.name %></h2>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="right-content card-box p-5 d-flex flex-column col-6">
      <h2 class="border-bottom pb-2">Your reservations</h2>

      <div class="wrapper-top my-4">

        <div class="wrapper-top d-flex align-items-center">
          <div id="signal-top"></div>
          <h5 class="ms-3">In progress :</h5>
        </div>

        <p class="pt-2">You have <strong><%= icours  %></strong> reservations in progress</p>
          <% @rentals.each do |rental| %>
            <%= link_to beast_path(rental.beast) do %>
              <% if ((Date.parse(rental.start_date.to_s).to_time.to_i - Time.now.to_i) < 0) && ((Date.parse(rental.end_date.to_s).to_time.to_i - Time.now.to_i) > 0)  %>
                <div class="card-product">
                  <%= cl_image_tag rental.beast&.photos&.first&.key, class: "img-placeholder-dashboard", style: "background-image", crop: :fill %>
                  <div class="card-infos ms-4 py-4 d-flex justify-content-between flex-column">
                    <div class="middle-card">
                      <p>Name: <%= rental.beast.name %></p>
                      <p>Rentals from: <%=rental.start_date %> To: <%=rental.end_date %> </p>
                      <p>Location: <%= rental.beast.user.address %></p>
                    </div>
                  </div>
                </div>
              <% end %>
            <% end %>
          <% end %>
      </div>

      <div class="middle-wrapper my-4">

        <div class="wrapper-top d-flex align-items-center">
          <div id="signal-middle"></div>
          <h5 class="ms-3">To come :</h5>
        </div>

        <p class="pt-2">You have <strong><%= ireservations  %></strong> reservations</p>
        <% @rentals.each do |rental| %>
          <%= link_to beast_path(rental.beast) do %>
            <% if (Date.parse(rental.start_date.to_s).to_time.to_i - Time.now.to_i) > 0 %>
            <div class="card-product">
              <%= cl_image_tag rental.beast&.photos&.first&.key, class: "img-placeholder-dashboard", style: "background-image", crop: :fill %>
              <div class="card-infos ms-4 py-4 d-flex justify-content-between flex-column">
                <div class="middle-card">
                  <p>Name: <%= rental.beast.name %></p>
                  <p>Rentals from: <%=rental.start_date %> To: <%=rental.end_date %> </p>
                  <p>Location: <%= rental.beast.user.address %></p>
                </div>
              </div>
            </div>
            <% end %>
          <% end %>
        <% end %>
      </div>

      <div class="bottom-wrapper my-4">

        <div class="wrapper-top d-flex align-items-center">
          <div id="signal-bottom"></div>
          <h5 class="ms-3">Past :</h5>
        </div>

        <p class="pt-2">You have <strong><%= ipastreservations  %></strong> reservations passed</p>
        <% @rentals.each do |rental| %>
          <%= link_to beast_path(rental.beast) do %>
            <% if (Date.parse(rental.start_date.to_s).to_time.to_i - Time.now.to_i) < 0 %>
              <div class="card-product">
                <%= cl_image_tag rental.beast&.photos&.first&.key, class: "img-placeholder-dashboard", style: "background-image", crop: :fill %>
                <div class="card-infos ms-4 py-4 d-flex justify-content-between flex-column">
                  <div class="middle-card">
                    <p>Name: <%= rental.beast.name %></p>
                    <p>Rentals from: <%=rental.start_date %> To: <%=rental.end_date %> </p>
                    <p>Location: <%= rental.beast.user.address %></p>
                  </div>
                </div>
              </div>
              <div>
            <% end %>
          <% end %>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/pages/home.html.erb
<header class="header-main">

  <%= render "shared/navbar" %>

  <div class="header-card-wrapper w-100 px-5 pt-3">
    <div style="background-image: url('https://images.unsplash.com/photo-1528158222524-d4d912d2e208?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2040&q=80')" class="card-header">
      <div class="content-wrapper d-flex flex-column align-items-center mb-4">
        <h4>Nobody wants your Venomous Viper? <br> That's fine.</h4>
        <a href="/beasts" class="btn btn-default my-4">I am flexible</a>
      </div>
    </div>
  </div>

</header>

<section class="overview-section">
  <h3 class="section-title my-5">Super cute animals to take care of</h3>

<div class="container-fluid horizontal-bar-container">
    <div class="d-flex justify-content-between">


  <div class="card-sm flex-grow-1" style="background-color: #7db23c">
      <%= link_to beast_path(@selection[0]) do %>
    <img class="img-placeholder w-100" style="background-image: url('<%= cl_image_path @selection[0].photos.first.key %>')">
    <div class="card-infos">
      <h3><%= @selection[0].name %></h3>
      <p>42 kilometers away</p>
    </div>
      <% end %>
  </div>

  <div class="card-sm flex-grow-1" style="background-color: #284942">
      <%= link_to beast_path(@selection[1]) do %>
    <img class="img-placeholder w-100" style="background-image: url('<%= cl_image_path @selection[1].photos.first.key %>')">
    <div class="card-infos">
      <h3><%= @selection[1].name %></h3>
      <p>42 kilometers away</p>
    </div>
      <% end %>
  </div>

  <div class="card-sm flex-grow-1" style="background-color: #BDBD2C">
      <%= link_to beast_path(@selection[2]) do %>
    <img class="img-placeholder w-100" style="background-image: url('<%= cl_image_path @selection[2].photos.first.key %>')">
    <div class="card-infos">
      <h3><%= @selection[2].name %></h3>
      <p>34 kilometers away</p>
    </div>
      <% end %>
  </div>

  <div class="card-sm flex-grow-1 d-none d-xl-block" style="background-color: #7db23c">
      <%= link_to beast_path(@selection[3]) do %>
    <img class="img-placeholder w-100" style="background-image: url('<%= cl_image_path @selection[3].photos.first.key %>')">
    <div class="card-infos">
      <h3><%= @selection[3].name %></h3>
      <p>60 kilometers away</p>
    </div>
      <% end %>
  </div>

  <div class="card-sm flex-grow-1 d-none d-lg-block" style="background-color: #7B7E6C">
      <%= link_to beast_path(@selection[4]) do %>
    <img class="img-placeholder w-100" style="background-image: url('<%= cl_image_path @selection[4].photos.first.key %>')">
    <div class="card-infos">
      <h3><%= @selection[4].name %></h3>
      <p>60 kilometers away</p>
    </div>
      <% end %>
  </div>

</div>
</section>

<section class="asking-section px-5 my-5">
  <div class="img-placeholder">
  <div class="content-wrapper">
    <h3>Questions about the reception of your companions?</h3>
    <a href="" class="btn btn-default my-5">Asking questions of survivors</a>
  </div>
  </div>
</section>

<footer class="footer w-100">
  <div class="top">
    <p>Ready for an unforgettable experience?</p>
    <h2 class="mb-4">Sign up now!</h2>
    <a href="#" class="btn btn-default my-4">Get me in!</a>
  </div>
  <p>Copyright © 2022. airbnbeast. All rights reserved.</p>
</footer>


        <%= render "beasts/beast_form" %>

app/views/rentals/index.html.erb
<h1>My rentals</h1>
<ul>
  <% @rentals.each do |rental| %>
    <li><%= rental.status %></li>
  <% end %>
</ul>
<p><%= link_to "Add a rental", new_user_rental_path(@user)%></p>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

app/views/shared/_navbar.html.erb
<div class="sticky-navbar">
  <div class="navbar-wrapper px-5 py-3">

    <nav class="navbar">
      <%= link_to "airbnbeast", root_path, class: 'brand-logo' %>
      <%= render "pages/dropdown_user", user: @user %>
    </nav>

    <div class="search-wrapper">
      <%= form_tag(beasts_path, {method: :get, class: 'searchbar py-3 ps-5 pe-3 w-100'}) do %>
        <div class='form-control border-0 border-right search-items pe-4 border-end'>
          <%= label_tag :query, 'Find your beast' %>
          <%= text_field_tag :query,
            params[:query],
            placeholder: "Crocodile"
          %>

        </div>
        <div class='form-control border-0 border-right search-items pe-4 border-end'>
          <%= label_tag 'Start date' %>
          <%= text_field_tag :start_date,
            params[:start_date],
            placeholder: "Today!",
            as: :string, input_html: { id: "start_date" }
          %>
        </div>
        <div class='form-control border-0 border-right search-items'>
          <%= label_tag 'End date' %>
          <%= text_field_tag :end_date,
            params[:end_date],
            placeholder: "If you survive!",
            as: :string, input_html: { id: "end_date" }
          %>
        </div>
        <%= button_tag(beasts_path, {class: "btn rounded-green-btn d-flex align-items-center justify-content-center px-4"}) do %>
          <i class="fa-solid fa-magnifying-glass"></i>
        <% end %>
      <% end %>
    </div>
  </div>
</div>